# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Eventsourcing
description: GetEventStore store implementation.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/eventsource-api
library:
  default-extensions:
    - NoImplicitPrelude
  dependencies:
  - base >=4.9 && <5
  - protolude >=0.1.10 && <0.3
  - eventstore >=0.14 && <0.16
  - eventsource-api >= 1.1
  - aeson
  - mtl
  source-dirs: library
license: BSD3
license-file: LICENSE.md
author: Yorick Laupa
maintainer: yo.eight@gmail.comm
name: eventsource-geteventstore-store
synopsis: GetEventStore store implementation.
tests:
  geteventstore-store-test-suite:
    dependencies:
    - base
    - eventsource-geteventstore-store
    - eventsource-api
    - eventsource-store-specs ==1.*
    - eventstore
    - tasty
    - tasty-hspec
    - protolude
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '1.0.4'
