# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Eventsourcing
description: Please read README.md.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/eventsource-api
library:
  default-extensions:
    - NoImplicitPrelude
  dependencies:
    - base >=4.9 && <5
    - protolude >= 0.1.10 && <0.2
    - uuid
    - aeson
    - mtl
    - containers
    - unordered-containers
  source-dirs: library
license: BSD3
license-file: LICENSE.md
author: Yorick Laupa
maintainer: yo.eight@gmail.com
name: eventsource-api
synopsis: Provides a eventsourcing high level API.
version: '1.0.2'
