# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Eventsourcing
description: Please read README.md.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/eventsource-api
library:
  default-extensions:
    - NoImplicitPrelude
  dependencies:
    - base >=4.9 && <5
    - classy-prelude ==1.0.*
    - uuid
    - aeson
    - mtl
    - containers
  source-dirs: library
license: BSD3
maintainer: Yorick Laupa
name: eventsource-api
synopsis: Provides a eventsourcing high level API.
tests:
  eventsource-api-test-suite:
    default-extensions:
    - NoImplicitPrelude

    dependencies:
    - base
    - eventsource-api
    - tasty
    - tasty-hspec
    - classy-prelude
    - aeson
    - mtl
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '1.0.0'
