# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Eventsourcing, Testing
description: Provides common test specification for Store implementation.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
ghc-options: -Wall
github: YoEight/eventsource-api
library:
  default-extensions:
    - NoImplicitPrelude
  dependencies:
  - base >=4.9 && <5
  - protolude >= 0.1.10 && <0.3
  - eventsource-api ==1.*
  - tasty
  - tasty-hspec
  - mtl
  - aeson
  - uuid
  source-dirs: library
license: BSD3
license-file: LICENSE.md
author: Yorick Laupa
maintainer: yo.eight@gmail.com
name: eventsource-store-specs
synopsis: Provides common test specification for Store implementation.
version: '1.0.1'
